### ISSUE TITLE
Traceback (most recent call last):   File "harmony.py", line 19, in <module>   File "songs.py", line 44, in listTracks   File "functions.py", line 140, in getSongs KeyError: 'results' [96945] Failed to execute script 'harmony' due to unhandled exception!

### ISSUE THREAD

**Issue by KG691** [ZingyTomato/Harmony-Music#2]
Traceback (most recent call last):
  File "harmony.py", line 19, in <module>
  File "songs.py", line 44, in listTracks
  File "functions.py", line 140, in getSongs
KeyError: 'results'
[96945] Failed to execute script 'harmony' due to unhandled exception!

**Comment by ZingyTomato** [comment]
Fixed now with the new release.
https://github.com/ZingyTomato/Harmony-Music/releases/tag/v0.5.2
